openapi: 3.0.0
info:
  title: SIMPLE API
  version: 1.0.0
paths:
  /insertProduct/with-payload:
    post:
      tags:
        - "product"
      summary: Insert a product with a Json payload
      operationId: insertProductPayload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSchema'
      responses:
        '200':
          description: Product inserted Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

  /insertProduct/with-params:
    post:
      tags:
        - "product"
      summary: Insert a product with parameters
      operationId: insertProductParams
      parameters:
        - name: name
          in: query
          description: name of product
          required: true
          schema:
            type: string
        - name: product_id
          in: query
          description: ID of product
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product inserted Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'

components:
  schemas:
    ProductSchema:
      type: object
      properties:
        name:
          type: string
        product_id:
          type: string
    ProductResponse:
      type: object
      properties:
        message:
          type: string