openapi: 3.0.0
info:
  title: SIMPLE API
  version: 1.0.0
paths:
  /get-greeting:
    get:
      summary: Get a greeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string